project:
  type: book

book:
  title: "Your Project Title"
  chapters:
    - index.qmd
    - chapters/introduction.qmd
    - chapters/methods.qmd
    - chapters/results.qmd

format:
  html:
    theme: cosmo
